config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #CRUD for users
  resources :users


  #Create user account
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/user' => 'users#show'

  # CRUD for orders.
  resources :orders

  # Create or destroy a user session
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  # Rates
  get '/rates' => 'rates#index'
  get '/rates/new' => 'rates#new'
  post '/rates' => 'rates#create'
  get '/rates/:id' => 'rates#show'

  # Index route
  get '/' => 'rates#index'
end

app/models/order.rb
# Order model, contains the following elements:
# @deadline - Date set by the user
# @created - Date set automatically to today when created
# @has - String for currency code
# @wants - String for currency code
# @amount - Decimal for the amount of money that the user wants to convert.
class Order < ApplicationRecord
  # Validates if the date is not earlier than today and no later than 5 years
  # from now.
  validate :deadline_not_in_the_past,
           :deadline_not_later_than_1_year,
           :creation_date_not_in_the_future

  validates :amount, presence: true

  # Custom validation options
  # deadline no later than a year from now:
  def deadline_not_later_than_1_year
    if deadline.present? && deadline > Date.today + 1.year
      errors.add(:deadline, 'cannot be later than 1 years from today.')
    end
  end

  # Deadline is not earlier that today.
  def deadline_not_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, 'cannot be in the past')
    end
  end

  def creation_date_not_in_the_future
    if created.present? && created > Date.today
      errors.add(:created, 'cannot be in the future')
    end
  end

  # Belongs to one user
  belongs_to :user

  # Has multiple related averages.
  has_many :averages
  has_and_belongs_to_many :averages
end

app/controllers/orders_controller.rb
# Orders controller, single, most important part of the application.
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where user: current_user
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @days = (@order.deadline - @order.created).to_i
    @averages = @order.averages.order('date asc')
    @rate = Rate.find_for_week(@order.created.to_s)

    @averages.each do |average|
      average.computed_rate = average[@order.has.downcase] / average[@order.wants.downcase]
    end

    redirect_to '/signin' if @order.user != current_user
  end

  # GET /orders/new
  def new
    @order = Order.new

    redirect_to '/signin' if current_user.nil?
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = User.find(current_user)

    respond_to do |format|
      if @order.save
        GetCurrencyHistoryJob.perform_now(@order)
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @averages = @order.averages.order('date asc')

    respond_to do |format|
      if @order.update(order_params)
        GetCurrencyHistoryJob.perform_now(@order)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def order_params
    params.require(:order).permit(:has, :wants, :amount, :deadline)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="form-horizontal">
  <%= form_for(order) do |f| %>
      <% if order.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being
              saved:</h2>

            <ul>
              <% order.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label "I have" %>
        <%= f.select :has, choices: (['EUR', 'AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'GBP', 'HKD', 'HRK', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'RON', 'RUB', 'SEK', 'SGD', 'THB', 'TRY', 'USD', 'ZAR']), class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :amount %>
        <%= f.text_field :amount, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "I want" %>
        <%= f.select :wants, choices: (['USD', 'AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP', 'HKD', 'HRK', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'RON', 'RUB', 'SEK', 'SGD', 'THB', 'TRY', 'ZAR']), class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label "I can wait until" %>
        <%= f.date_select :deadline, start_year: Date.today.year, default: 1.month.from_now, end_year: Date.today.year + 1, class: "form-control" %>
      </div>

      <div class="actions">
        <div align="right">
          <%= f.submit "Calculate", class: "btn btn-primary" %>
        </div>
      </div>
  <% end %>
</div>

app/views/orders/_graph.html.erb
<% first_rate_value = (@order.amount / (@rate[@order.has.downcase] / @rate[@order.wants.downcase])) %>
<% top_three = @averages.sort_by(&:computed_rate).reverse %>
<% graph_dates = [] %>
<% graph_dates << @rate.date.strftime('%Y %B %d') %>
<% graph_values = [] %>
<% graph_values << first_rate_value %>

<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-9">
    <h3 align="center">Details for each week, standarized to Wednesdays</h3>
    <p></p>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>When</th>
        <th>History</th>
        <th>Average from last 2 years</th>
        <th>Will have</th>
        <th>Profit/loss</th>
        <th>Rank</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th>On the day of creation: <%= @rate.date.strftime('%Y %B %d') %></th>
        <th> N/A</th>
        <th>1 <%= @order.wants %>
          was <%= number_with_precision((@averages.first[@order.has.downcase] / @averages.first[@order.wants.downcase]), :precision => 4) %> <%= @order.has %></th>
        <th><%= number_with_precision((@order.amount / (@rate[@order.has.downcase] / @rate[@order.wants.downcase])), :precision => 2) %> <%= @order.wants %></th>
        <th>
          <div align="center">0.00</div>
        </th>
        <th>
        </th>
      </tr>
      <% @averages[1..@averages.length].each_with_index do |average, index| %>
          <% previous_element = @averages[index-1] %>
          <%= %>
          <% real_rate = (average[@order.has.downcase] / average[@order.wants.downcase]) %>
          <% real_value = (@order.amount / (average[@order.has.downcase] / average[@order.wants.downcase])) %>
          <% proportion = (@order.amount / (@rate[@order.has.downcase] / @rate[@order.wants.downcase])) * (@order.amount / (previous_element[@order.has.downcase] / previous_element[@order.wants.downcase])) / real_value %>
          <% graph_values << proportion %>
          <% graph_dates << (average.date + 1.year).strftime('%Y %B %d') %>
          <tr>
            <td><%= (average.date + 1.year).strftime('%Y %B %d, %W week of %Y') unless average.date == nil %>
            </td>
            <td><%= average.date.strftime('%Y %B %d') %></td>
            <td>1 <%= @order.wants %>
              was <%= number_with_precision(real_rate, :precision => 4) %> <%= @order.has %></td>
            <td><%= number_with_precision(proportion, :precision => 2) %> <%= @order.wants %></td>
            <% if first_rate_value - proportion >= 0 %>
                <td>
                  <p><%= number_with_precision(proportion - first_rate_value, :precision => 2) %> &darr;  </p>
                </td>
            <% else %>
                <td>
                  <p><%= number_with_precision(proportion - first_rate_value, :precision => 2) %> &uarr;  </p>
                </td>
            <% end %>
            <% case average
                 when top_three.first %>
                <td>1st</td>
            <% when top_three.second %>
                <td>2nd</td>
            <% when top_three.third %>
                <td>3rd</td>
            <% else %>
                <td></td>
            <% end %>
      <% end %>
      </tr>

      </tbody>
    </table>
    <script type="application/javascript">
      document.addEventListener('DOMContentLoaded', function () {
        new Chartist.Line('.ct-chart', data, {
          showArea: true
        });
      });

      var data = {
        labels: <%= graph_dates.to_json.html_safe %>,
        series: [
          <%= graph_values.to_json.html_safe %>
        ]
      };

    </script>
  </div>
</div>

app/views/orders/edit.html.erb
<div class="container-fluid">
  <div class="col-md-3"></div>
  <div class="col-md-9">
    <h2>Editing Order</h2>

    <%= render 'form', order: @order %>

    <%= link_to 'Show', @order %> |
    <%= link_to 'Back', orders_path %>
  </div>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-3">
</div>
<div class="col-md-9">
  <h2>My Orders</h2>

  <table class="table table-hover">
    <thead>
    <tr>
      <th>Has</th>
      <th>Wants</th>
      <th>Amount</th>
      <th>Deadline</th>
      <th colspan="3">
        <div align="center">Actions</div>
      </th>
    </tr>
    </thead>

    <tbody>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.has %></td>
          <td><%= order.wants %></td>
          <td><%= order.amount %></td>
          <td><%= order.deadline %></td>
          <td><%= link_to 'Show', order %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <div class="col-md-pull-3" align="right">
    <br><br>
    <%= link_to 'New Order', '/orders/new', class: 'btn btn-primary', id: "order-new" %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="col-md-3"></div>
<div class="col-md-9">
  <h2>New Order</h2>

  <%= render 'form', order: @order %>

  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <div align="center">
      <h2>Viewing order:</h2>
    </div>
    <dl class="dl-horizontal">
      <dt><strong>Has:</strong></dt>
      <dd><%= @order.has %> <%= @order.amount %></dd>
      <dt><strong>Wants:</strong></dt>
      <dd> <%= @order.wants %></dd>
      <dt><strong>Created:</strong></dt>
      <dd><%= @order.created.to_date %></dd>
      <dt><strong>Deadline:</strong></dt>
      <dd><%= @order.deadline %></dd>
    </dl>
    <div align="center">
      <%= link_to 'Edit', edit_order_path(@order), class: 'btn btn-primary', id: 'btn-edit' %> |
      <%= link_to 'Back', orders_path, class: 'btn btn-primary', id: 'btn-back' %>
    </div>
    <h3>How is it computed?</h3>
    <p align="justify">We take average values from the last 2 years and the current rate. Then, we
      calculate a
      proportion between two
      neighbouring averages in history. Finally, we apply that proportion to current rate and
      value.</p>
    <h4>Example</h4>
    <p align="justify">In the last two years, between weeks 10 and 11 the EUR/USD rate rose from 1 to 1.50. Currently,
      it's week 10, and the rate is at 0.5.</p>
    <p>Based on the past, we predict that the date will rise to 0.75.</p>

    <h4>Note:</h4>
    <p>Sometimes, getting the average data for a long period can take some time. Refresh the page if
      needed.</p>

  </div>
  <div class="col-md-9">
    <div align="center">
      <h3>Graph</h3>
      <div class="ct-chart ct-perfect-fourth"></div>
    </div>
    <br>
  </div>
</div>
    <%= render 'graph' %>