config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #CRUD for users
  resources :users


  #Create user account
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/user' => 'users#show'

  # CRUD for orders.
  resources :orders

  # Create or destroy a user session
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  # Rates
  get '/rates' => 'rates#index'
  get '/rates/new' => 'rates#new'
  post '/rates' => 'rates#create'
  get '/rates/:id' => 'rates#show'

  # Index route
  get '/' => 'rates#index'
end

app/models/rate.rb
# Model for rates, contains the following elements:
# @date for which was creted.
# @record_date which was returned from fixer API
# @orders that are connected with it
# @fetch_completed, bool that becomes true once the fetch is done.
# Multiple numerical value, one for each currency
class Rate < ApplicationRecord
  validates :date, uniqueness: true

  has_many :orders
  has_and_belongs_to_many :orders

  # Define a computed rate that is set on every order
  attr_accessor :computed_rate


  # Find unique record for that particular week
  def self.find_for_week(date_string)
    date = Date.parse(date_string)
    # Get to the beginning of a week, then add 3 for Wednesday
    wednesday = date - date.wday + 3
    puts wednesday
    record = Rate.first_or_create(date: wednesday)

    FetchRateJob.perform_later(record) unless record.fetch_completed

    record
  end

  # This job is similar to the one above, but accepts date objects straight
  # from the Order class.
  def self.find_history(date)
    record = Rate.where(date: date)

    record.create(date: date) if record.nil?

    FetchRateJob.perform_later(record) if record.fetch_complete == false
  end
end

app/controllers/rates_controller.rb
# Controller for rates, those are displayed on the index page.
class RatesController < ApplicationController
  # GET /rates
  def index
    @rates = Rate.all.order('date desc')
    @rates.each do |r|
      FetchRateJob.perform_later(r) unless r.fetch_completed
    end
  end

  # GET /rates/{id}
  def show
    @rate = Rate.find(params[:id])
  end

  # Get /rates/new
  def new
    @rate = Rate.new
  end

  # POST /rates/new
  def create
    @rate = Rate.find_for_week(params[:date])
    redirect_to '/rates'
  end

  def set_rate
    @rate = Rate.find_by(params[:id])
  end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-3">
  <h3>Getting started</h3>
  <p>What you see here is a list of existing currency rates by week. To find when it is the most
    convenient time to exchange once currency to another, do the following:</p>
  <ul>
    <li ><%= link_to 'Create an acccount', '/signup' %><br>
      or <%= link_to 'Sign in', '/signin' %></li>
    <li ><%= link_to 'Create a new order', '/orders/new' %></li>
  </ul>
</div>
<div class="col-md-9">
  <h2>Rates</h2>

  <table class="table table-responsive">
    <thead>
    <tr>
      <th>Week of a year</th>
      <th>Date of the probe</th>
      <th>EUR</th>
      <th>USD</th>
      <th>CAD</th>
      <th>JPY</th>
      <th>SEK</th>
      <th>CHF</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @rates.each do |rate| %>
        <tr>
          <td><%= rate.date.strftime('%W week of %Y') %></td>
          <td><%= rate.record_date.strftime('%Y-%m-%d, %A') unless rate.record_date == nil %></td>
          <td><%= rate.eur %></td>
          <td><%= rate.usd %></td>
          <td><%= rate.cad %></td>
          <td><%= rate.jpy %></td>
          <td><%= rate.sek %></td>
          <td><%= rate.chf %></td>
          <td><%= link_to 'Show', controller: "rates", action: "show", id: rate.id %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/rates/new.html.erb
<h2>Select the date:</h2>

<%= form_tag '/rates' do %>

    <div class="field form-group">
      Date: <%= date_field_tag :date, type: 'date' %>
    </div>

    <div class="form-group">
      <%= submit_tag "Submit", class: 'form-control' %>
    </div>

<% end %>

app/views/rates/show.html.erb
<div class="col-md-3"></div>
<div class="col-md-9">
  <p id="notice"><%= notice %></p>

  <h2>Rates for <%= @rate.date.strftime('%W week of %Y') %></h2>
  <p><strong>Note:</strong> We standarize rates to Wendesday of a given week. Actual record date might vary on different factors. For example, if that day was a bank holiday.</p>

  <dl class="dl-horizontal">
    <dt>Date</dt>
    <dd><%= @rate.date.strftime("%Y %B %d") %></dd>
    <dt>Record date</dt>
    <dd><%= @rate.record_date.strftime("%Y %B %d, %A") %></dd>
    <br>
    <dt>EUR</dt>
    <dd><%= @rate.eur %></dd>
    <dt>AUD</dt>
    <dd><%= @rate.aud %></dd>
    <dt>BGN</dt>
    <dd><%= @rate.bgn %></dd>
    <dt>BRL</dt>
    <dd><%= @rate.brl %></dd>
    <dt>CAD</dt>
    <dd><%= @rate.cad %></dd>
    <dt>CHF</dt>
    <dd><%= @rate.chf %></dd>
    <dt>CNY</dt>
    <dd><%= @rate.cny %></dd>
    <dt>CZK</dt>
    <dd><%= @rate.czk %></dd>
    <dt>DKK</dt>
    <dd><%= @rate.dkk %></dd>
    <dt>GBP</dt>
    <dd><%= @rate.gbp %></dd>
    <dt>HKD</dt>
    <dd><%= @rate.hkd %></dd>
    <dt>HRK</dt>
    <dd><%= @rate.hrk %></dd>
    <dt>HUF</dt>
    <dd><%= @rate.huf %></dd>
    <dt>IDR</dt>
    <dd><%= @rate.idr %></dd>
    <dt>ILS</dt>
    <dd><%= @rate.ils %></dd>
    <dt>INR</dt>
    <dd><%= @rate.inr %></dd>
    <dt>JPY</dt>
    <dd><%= @rate.jpy %></dd>
    <dt>KRW</dt>
    <dd><%= @rate.krw %></dd>
    <dt>MXN</dt>
    <dd><%= @rate.mxn %></dd>
    <dt>MYR</dt>
    <dd><%= @rate.myr %></dd>
    <dt>NOK</dt>
    <dd><%= @rate.nok %></dd>
    <dt>NZD</dt>
    <dd><%= @rate.nzd %></dd>
    <dt>PHP</dt>
    <dd><%= @rate.php %></dd>
    <dt>PLN</dt>
    <dd><%= @rate.pln %></dd>
    <dt>RON</dt>
    <dd><%= @rate.ron %></dd>
    <dt>SEK</dt>
    <dd><%= @rate.sek %></dd>
    <dt>SGD</dt>
    <dd><%= @rate.sgd %></dd>
    <dt>THB</dt>
    <dd><%= @rate.thb %></dd>
    <dt>TRY</dt>
    <dd><%= @rate.try %></dd>
    <dt>USD</dt>
    <dd><%= @rate.usd %></dd>
    <dt>ZAR</dt>
    <dd><%= @rate.zar %></dd>
  </dl>

  <div align="right">
    <%= link_to 'Back', rates_path, class: 'btn btn-primary', id: 'btn-back' %>
  </div>
</div>